version: '3'

services:
    db:
        image: postgres
        environment: 
            POSTGRES_HOST_AUTH_METHOD: 'trust'
    web:
        build: .
        command: flask run --host=0.0.0.0
        env_file: 
            - .env
        volumes:
            - .:/code
        ports:
            - '5000:5000'
        depends_on: 
            - db